# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 275)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sortEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sortEdit.setGeometry(QtCore.QRect(150, 40, 181, 20))
        self.sortEdit.setObjectName("sortEdit")
        self.tasteEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tasteEdit.setGeometry(QtCore.QRect(150, 130, 181, 20))
        self.tasteEdit.setObjectName("tasteEdit")
        self.sizeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sizeEdit.setGeometry(QtCore.QRect(150, 190, 181, 20))
        self.sizeEdit.setObjectName("sizeEdit")
        self.priceEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceEdit.setGeometry(QtCore.QRect(150, 160, 181, 20))
        self.priceEdit.setObjectName("priceEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 131, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 131, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 131, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 131, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 190, 131, 20))
        self.label_7.setObjectName("label_7")
        self.beansBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.beansBox.setGeometry(QtCore.QRect(150, 100, 181, 22))
        self.beansBox.setObjectName("beansBox")
        self.beansBox.addItem("")
        self.beansBox.addItem("")
        self.roastingBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.roastingBox.setGeometry(QtCore.QRect(150, 70, 181, 22))
        self.roastingBox.setObjectName("roastingBox")
        self.roastingBox.addItem("")
        self.roastingBox.addItem("")
        self.roastingBox.addItem("")
        self.addBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(20, 230, 311, 31))
        self.addBtn.setObjectName("addBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "sort"))
        self.label_3.setText(_translate("MainWindow", "roasting"))
        self.label_4.setText(_translate("MainWindow", "ground/beans"))
        self.label_5.setText(_translate("MainWindow", "taste"))
        self.label_6.setText(_translate("MainWindow", "price"))
        self.label_7.setText(_translate("MainWindow", "size"))
        self.beansBox.setItemText(0, _translate("MainWindow", "ground"))
        self.beansBox.setItemText(1, _translate("MainWindow", "beans"))
        self.roastingBox.setItemText(0, _translate("MainWindow", "bright"))
        self.roastingBox.setItemText(1, _translate("MainWindow", "medium"))
        self.roastingBox.setItemText(2, _translate("MainWindow", "dark"))
        self.addBtn.setText(_translate("MainWindow", "Добавить"))
